#!/usr/bin/env bash
# Builds the C# installer core as a NativeAOT static library and wires it into
# the Xcode app: copies libNativeUmm.a, stages the UMM payload as app resources,
# and regenerates NativeUmm.xcconfig with the (version-specific) link flags.
#
# Re-run this whenever the C# changes or the .NET runtime pack version changes.
set -euo pipefail
cd "$(dirname "$0")"                       # UnityModManagerMac/
ROOT="$(pwd)"
RID="osx-arm64"

echo "==> publish NativeAOT static lib ($RID)"
dotnet publish NativeUmm/NativeUmm.csproj -c Release -r "$RID" >/dev/null
SRC_A="NativeUmm/bin/Release/net10.0/$RID/native/NativeUmm.a"
[ -f "$SRC_A" ] || { echo "ERROR: $SRC_A not produced"; exit 1; }

mkdir -p NativeUmm/lib
cp "$SRC_A" NativeUmm/lib/libNativeUmm.a
echo "    -> NativeUmm/lib/libNativeUmm.a"

echo "==> stage UMM payload as app resources"
# Project-root Payload/ is referenced as a folder ref in the Xcode Resources
# phase, so it lands intact at Contents/Resources/Payload/ in the .app.
PAYLOAD_SRC="../MacTuiInstaller/payload"
PAYLOAD_DST="Payload"
rm -rf "$PAYLOAD_DST"; mkdir -p "$PAYLOAD_DST"
cp "$PAYLOAD_SRC"/UnityModManager.dll \
   "$PAYLOAD_SRC"/UnityModManager.xml \
   "$PAYLOAD_SRC"/0Harmony.dll \
   "$PAYLOAD_SRC"/dnlib.dll \
   "$PAYLOAD_SRC"/System.Xml.dll \
   "$PAYLOAD_DST"/
echo "    -> $PAYLOAD_DST ($(ls "$PAYLOAD_DST" | wc -l | tr -d ' ') files)"

echo "==> resolve NativeAOT runtime pack"
DOTNET_LIBEXEC="$(brew --prefix dotnet 2>/dev/null)/libexec"
PACK="$(ls -d "$DOTNET_LIBEXEC"/packs/Microsoft.NETCore.App.Runtime.NativeAOT.$RID/*/runtimes/$RID/native 2>/dev/null | sort -V | tail -1)"
[ -d "$PACK" ] || { echo "ERROR: NativeAOT runtime pack not found under $DOTNET_LIBEXEC/packs"; exit 1; }
echo "    -> $PACK"

echo "==> resolve brew openssl@3 + brotli"
SSL="$(brew --prefix openssl@3)/lib"
BROTLI="$(brew --prefix brotli)/lib"
for f in "$SSL/libssl.a" "$SSL/libcrypto.a" "$BROTLI/libbrotlienc.a" "$BROTLI/libbrotlidec.a" "$BROTLI/libbrotlicommon.a"; do
  [ -f "$f" ] || { echo "ERROR: missing static lib $f (brew install openssl@3 brotli)"; exit 1; }
done

echo "==> write NativeUmm.xcconfig"
cat > NativeUmm.xcconfig <<EOF
// GENERATED by build-native.sh — do not edit by hand.
// Links the NativeAOT C# installer core (libNativeUmm.a) + its .NET runtime
// dependencies into the Swift app, producing a single self-contained binary.

NATIVE_PACK = $PACK
SSL_LIB = $SSL
BROTLI_LIB = $BROTLI

SWIFT_OBJC_BRIDGING_HEADER = \$(SRCROOT)/NativeUmm/NativeUmm-Bridging-Header.h

// The installer writes into the Steam game folder, outside any sandbox container.
ENABLE_APP_SANDBOX = NO

OTHER_LDFLAGS = \$(inherited) -Xlinker -force_load -Xlinker \$(SRCROOT)/NativeUmm/lib/libNativeUmm.a \$(NATIVE_PACK)/libbootstrapperdll.o \$(NATIVE_PACK)/libRuntime.WorkstationGC.a \$(NATIVE_PACK)/libeventpipe-disabled.a \$(NATIVE_PACK)/libstandalonegc-disabled.a \$(NATIVE_PACK)/libaotminipal.a \$(NATIVE_PACK)/libstdc++compat.a \$(NATIVE_PACK)/libSystem.Native.a \$(NATIVE_PACK)/libSystem.IO.Compression.Native.a \$(NATIVE_PACK)/libSystem.Net.Security.Native.a \$(NATIVE_PACK)/libSystem.Security.Cryptography.Native.Apple.a \$(SSL_LIB)/libssl.a \$(SSL_LIB)/libcrypto.a \$(BROTLI_LIB)/libbrotlienc.a \$(BROTLI_LIB)/libbrotlidec.a \$(BROTLI_LIB)/libbrotlicommon.a -lz -licucore -lobjc -ldl -lc++ -framework CoreFoundation -framework Foundation -framework Security -framework Network -framework GSS -framework CryptoKit
EOF
echo "    -> NativeUmm.xcconfig"

echo
echo "Done. Open UnityModManagerMac.xcodeproj and build, or:"
echo "  xcodebuild -project UnityModManagerMac.xcodeproj -scheme UnityModManagerMac -configuration Debug build"
